global_costmap:
   global_frame: /map
   robot_base_frame: /base_link
   update_frequency: 5.0
   publish_frequency: 2.0
   static_map: true
   
   transform_tolerance: 0.5
   rolling_window : false
   
   plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: laser_layer,          type: "costmap_2d::obstacle_layer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

